language: rust

cache: cargo

branches:
  only:
    - master
    - staging
    - trying

matrix:
  fast_finish: true
  include:

  # Run tests + checks against stable
  - rust: stable
    name: "itsdangerous-rs on stable"
    script: ./ci/tests.sh

  # Check formatting.
  - rust: stable
    name: "rustfmt"
    script: ./ci/rustfmt.sh