[package]
name = "itsdangerous"
version = "0.1.0"
authors = ["Jake <jh@discordapp.com>"]
edition = "2018"

[dependencies]
hmac = "0.7.0"
sha-1 = "0.8.1"
base64 = "0.10.1"
generic-array = "0.12.0"
typenum = "1.10.0"
serde = "1.0"
serde_json = "1.0"